# Generated by Django 4.1.5 on 2023-02-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecompra', models.CharField(max_length=80)),
                ('fechaCompra', models.DateField()),
                ('montoCompra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('DNI', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreVenta', models.CharField(max_length=80)),
                ('fechaVenta', models.DateField()),
                ('montoVenta', models.IntegerField()),
            ],
        ),
    ]
